x=int(input("Please enter first number:"))
y=int(input("Please enter second number:"))
z=int(input("Please enter third number:"))
print("Max result is=>")
print(max(x,y,z))
input("Please press enter to exit")
exit()
